### PR TITLE
Date, social, summary, RSS enhacements

### PR DESCRIPTION
**Pull request by okelet**
This PR adds some tweaks/enhacements.

## Changes / fixes

- Add page option showDate (useful to set to false for non-post pages, like about)
- Add page option showShare (useful to set to false for non-post pages, like about)
-  Hide IntroDescription and "Read more" link if IntroDescription is empty in sidebar
- Use existing summary or abstract params if set; no need to truncate Summary, as Summary is already truncated automatically.
-  Enhanced rss.xml, respecting mainSections parameter 

## Screenshots (if applicable)

(prefer animated gif)

## Checklist

_Ensure you have checked off the following before submitting your PR._

- [x] tested locally with the [latest release of Hugo](https://github.com/gohugoio/hugo/releases). This requirement is [a standard](https://github.com/gohugoio/hugoThemes#theme-maintenance)
- [-] added new dependencies
- [x] updated the [docs]() ⚠️

### CODE REVIEW

**Comment by onweru** [comment]
@okelet @chipzoller, this PR [is a train](https://www.reddit.com/r/ProgrammerHumor/comments/a4zbpz/bulky_prs/).

**Comment by okelet** [comment]
Forget it.

**Comment by chipzoller** [comment]
@onweru what's the problem here? This is not an extensive PR and I see no issues with it on my side.

**Comment by onweru** [comment]
My bad, I meant to say that there are several issues covered in this PR; it would take me a while to do the review. Upon reviewing this, ad6b093 would need reverting even if I accepted.

I think we should include a PR template that would require folks to submit scoped PRs, ie. one issue per PR. Those ones are easier to review.

**Pull request merged**
