### PR TITLE
Removing image error display, and related cleanup

### LINKED ISSUE #266: cannot load web image, "image not found" error
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [y] Read the README.md
- [y] Have the extended version of Hugo installed
- [y] Used the exampleSite's config.toml as a reference
- [ ] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

Unable to load web image, it will prompt image not found.

Here is my [blog](https://111qqz.com/2019/10/The-Programming-Language-Course/)

I think there might be something wrong with this  [code](https://github.dev/chipzoller/hugo-clarity/blob/17e6574dd5c9a87ab1033538a4b426ce9e93f18a/layouts/_default/_markup/render-image.html#L25)

if I use a web image url,  then $fileDisk doesn't exist.
企业微信截图_16459602037280

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome

### PR DESCRIPTION
**Pull request by rootwork**
This PR...turned out to be way more involved than I thought it would be.

## Changes / fixes

- Fixes #266, I sure hope.

1. Moved the common formatting for images from content (`render-image.html`) and images from theme partials (`image.html`) into a single partial, `figure.html`, to reduce duplication. Unfortunately they can't be fully combined because the methods for getting certain page variables are different between content images and theme images.
2. Removed the image error partial and the `fileExists` check that called it.
3. Removed translations and a screenshot that were tied to that image error partial (this accounts for the number of files changed).
4. Added a call to `resources.GetRemote` when the image is remote, which lets Hugo [treat the remote image as local](https://gohugo.io/content-management/image-processing/#global-resources) and thus perform actions/get attributes on it. Images are placed in the `images` subdirectory of `public`.
5. Simplified (and possibly corrected) the generation of `srcset`s for other image formats. Incidentally concatenating strings in Hugo is [stupid and annoying and _has to be done in reverse_](https://blog.anantshri.info/concatinating-strings-in-hugo/), so readability in the "generate alternate image format tags" section is consequently terrible.
6. Improved how page assets were being called after I found [this little snippet](https://discourse.gohugo.io/t/how-to-use-image-processing-using-a-short-code/28264/6) from bep, who incidentally prefaces it with "we should come up with some canonical/best practice examples of doing these things … " (yeah!)
7. Sanitized paths and strings that hadn't been previously.
8. Added an example bundle page with a featured image and an inline image that illustrates the "modern images" support. It's now the most recent post listed.
9. Updated docs to clarify that the support for modern images is only possible when using page bundles. The forced full-path rewriting we had been doing using `fileExists` and loading the site config was an end run around [Hugo's restriction on processing images in `staticDir`](https://gohugo.io/content-management/image-processing/), but it was brittle and didn't work with themes loaded with Hugo modules. The updated documentation thus only promises this feature when using page bundles. (It should also work when using images in the `assets` directory, though Hugo Clarity doesn't do that.)

## Notes

- The `usePageBundles` param is _almost_ unnecessary, but in order to support both page bundles and not-page-bundles, I think it's better to keep it.

## Screenshots

**See captions under each screenshot for details**

content-image-basic, not using page bundles and thus unprocessed (note CSS class)")
A basic content image with no specified caption (thus using alt text), not using page bundles and thus unprocessed (note CSS class)

content-image-remote
A remote content image with specified caption, which Hugo processes and thus can add additional attributes

content-image-modern
A content image using page bundles in which a similarly-named .webp file exists, showing automated markup addition

thumbnail-image")
A thumbnail image in a content list; note alt text is the name of the parent post (this maintains existing behavior)

featured-image
A featured image, using a remote URL

## Suggested testing

1. Create a new test site using the `exampleSite` contents (this PR updates some of them)
2. Look at the images in the "Markdown Syntax Guide" post and the new "Using Hugo page bundles" post
3. Test adding images to existing or new posts with any combination of the following:
  a. local image
  b. remote image
  c. using/not using page bundles in sitewide configuration
  d. using/not using page bundles in an individual post
  e. with/without a specified caption (title)
  f. with a similarly named webp/avif/jxl file, if you want
  g. featured images
  h. thumbnail images, both in the main content list and in tag/category/series lists
  i. social images (this PR shouldn't affect them)

## Checklist

_Ensure you have checked off the following before submitting your PR._

- [x] tested locally with the [latest release of Hugo](https://github.com/gohugoio/hugo/releases). This requirement is [a standard](https://github.com/gohugoio/hugoThemes#theme-maintenance)
- [x] added new dependencies (n/a)
- [x] updated the [docs]() ⚠️

### CODE REVIEW

**Comment by rootwork** [comment]
The failing test on `0.89.4` is because `resources.GetRemote` [seems to have issues on older versions](https://answers.netlify.com/t/hugos-resources-getremote/53241) (I haven't been able to find out which one, specifically, fixed that error). Should I gate that behind a version check? How long does Hugo Clarity support older versions?

**Comment by chipzoller** [comment]
We've claim 0.63 as the minimum version, but glad to bump that up. It was never a hard-and-fast rule, just when we started. What updates are needed here?

**Comment by rootwork** [comment]
@chipzoller So it looks like the `resources.GetRemote` function changed somehow between 0.89.4 and the current version. The Netlify issue I linked to upthread said it was fixed by 0.94, but it might have been earlier than that. If you look at that issue it's exactly the same error we're getting on the 0.89.4 test: `can't evaluate field GetRemote in type interface {}`. Given that it does build just fine in the current version of Hugo I'm pretty sure it was some sort of internal bug that was present, and not a problem with the code.

If you think it's important to keep testing with older versions I don't want to stand in the way of that; I could see if it's possible to run this function only if it doesn't error, or alternatively I could just remove it until such time as we bump up the minimum version.

**Comment by rootwork** [comment]
OK, looks like `resources.GetRemote` was [added pretty recently](https://github.com/bep/hugo/commit/605c81d05e256bb80cb15cb8dca54661df35b133) -- Dec. 16, 2021, at some point after 0.89.0. (I will never understand why some functions in Hugo docs get marked with the versions that they were released on and some, [like `GetRemote`](https://gohugo.io/hugo-pipes/introduction/#get-resource-with-resourcesget-and-resourcesgetremote), are not marked at all.)

**Comment by chipzoller** [comment]
Again, so sorry, but need @onweru to review this as it's his domain primarily.

**Comment by zxkane** [comment]
+1, hope it to be reviewed soon.

**Review by onweru — APPROVED** [review]
All good 👍🏼

**Pull request merged**
