### PR TITLE
Display remote images correctly. Fixes #266

### LINKED ISSUE #266: cannot load web image, "image not found" error
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [y] Read the README.md
- [y] Have the extended version of Hugo installed
- [y] Used the exampleSite's config.toml as a reference
- [ ] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

Unable to load web image, it will prompt image not found.

Here is my [blog](https://111qqz.com/2019/10/The-Programming-Language-Course/)

I think there might be something wrong with this  [code](https://github.dev/chipzoller/hugo-clarity/blob/17e6574dd5c9a87ab1033538a4b426ce9e93f18a/layouts/_default/_markup/render-image.html#L25)

if I use a web image url,  then $fileDisk doesn't exist.
企业微信截图_16459602037280

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome

### PR DESCRIPTION
**Pull request by rootwork**
This PR...

## Fixes

- #266 

## Screenshots (if applicable)

This PR includes both a fix and an addition to the `markdown-syntax.*.md` files to document how images work and (I hope) prevent such a regression in the future. The fix and the content change are two separate commits in case you'd like the first but not the second. This is a screenshot of the post (with image sizes reduced so they'll fit in the screenshot):

fix-remote-image-loading_ss

While the images look the same, the first is loading the local image file and the second is loading the image from the GitHub repo. The error message is **intentional**, to show what happens when an image doesn't load.

## Checklist

_Ensure you have checked off the following before submitting your PR._

- [x] tested locally with the [latest release of Hugo](https://github.com/gohugoio/hugo/releases). This requirement is [a standard](https://github.com/gohugoio/hugoThemes#theme-maintenance)
- [x] added new dependencies (n/a)
- [x] updated the [docs]() ⚠️ (n/a)

### CODE REVIEW

**Comment by rootwork** [comment]
Hmm, OK, so the build is failing because I included an example of an image that didn't exist to demonstrate the error message for a broken image.

Should I take that out, include a screenshot of the error message instead, or something else?

**Comment by rootwork** [comment]
Also to echo what I said on #266, this may require a follow-up. I realized in fixing this that the hard-coded directories here:

https://github.com/chipzoller/hugo-clarity/blob/master/layouts/_default/_markup/render-image.html#L19-L22

will break in two other ways:

- when [images are loaded through Hugo modules](https://github.com/rootwork/hugo-module-site)
- when `contentDir` or `staticDir` is set to something other than the defaults

So just to mark those as needing follow-up. They are much less common than the bug that this PR fixes, however.

**Review by rahulwagh — APPROVED** [review]

**Comment by onweru** [comment]
@rootwork 

> Should I take that out, include a screenshot of the error message instead, or something else?

The latter please.

**Comment by rootwork** [comment]
@onweru Done.

**Comment by rootwork** [comment]
This is strange; it built successfully locally but is failing on this test. Let me see if I can figure it out.

**Comment by rootwork** [comment]
Just needed to copy the images to `exampleSite`. Ready to go now.

**Pull request merged**
