### PR TITLE
Provide git-trackable overrides

### LINKED ISSUE #28: Feature Request: Provide a git-trackable way to override theme variables/sass/js
In [custom CSS and JS in the README](https://github.com/chipzoller/hugo-clarity#custom-css-and-js) you explain how to add Sass and JS to the theme, and how to override color variables: By editing files within the Hugo Clarity theme.

I appreciate that you created the `custom.sass` and `custom.js` files.

But modifying these files presents a problem: You either have to choose to continue using the theme as a git submodule (in which case you can't track modifications) or you have to commit the theme directory as a regular part of your own git repo (in which case you can't update the theme as a submodule).

Changing the color variables is worse: Now you're hacking the theme files themselves, meaning you have the problem above _and_ if you ever update the theme, there will be merge conflicts.

Is there a way to provide support within the theme for custom Sass, JS and variable files **within the parent project's directory**? Perhaps in an `assets` directory of its own?

While it's true that right now you could override the CSS or JS in the parent project's directory, you can only do it by loading additional CSS/JS files (as you point out in that section of the README). And the only way to override the color variables -- because they're used throughout the theme's Sass files -- would be to replicate _all_ the rendered CSS that those color variables touch.

What do you think?

### PR DESCRIPTION
**Pull request by rootwork**
Fixes #28, and followup to #7.

### Changes
* Checks for `_variables.s[a|c]ss` file in `<projectroot>/assets/sass/` and overrides the default `_variables.sass` file in the theme. It loads this in the same place, thus the new variables cascade down into the other Sass partials. No additional CSS files are rendered.
* Checks for `_custom.s[a|c]ss` file in `<projectroot>/assets/sass/` and adds to the theme. Concatenated as before, so no additional CSS files are rendered.
* Checks for `custom.js` file in `<projectroot>/assets/js/` and concatenates into the JS. Concatenated as before, so no additional JS files are rendered.

### Caveats
* Currently in order for the custom variables file to be parsed properly, you have to fully duplicate the `_variables.sass` file from the theme -- i.e. you can't just have a file with a new `$light` value, you have to copy over the whole file and then change that one line. I'm not sure why this is true; it must be something about the Sass inheritance.
* I've left the `_custom.sass` file (and the check for it) in place in the theme. If this seems no longer necessary (I would say so) it could be removed, but I wanted to minimize disruption.
* I've also left the `custom.js` file in the theme; same as above.
* Currently it relies on the user to create the `assets`, `assets/sass` and `assets/js` directories if they want them. An alternative would be to create these directories, with stub files, in the `exampleSite` directory so they're already there. Again, wanted to disrupt as little as possible.
* Relevant documentation in `README.md` should be updated depending on the decisions above.

### CODE REVIEW

**Comment by onweru** [comment]
@rootwork, I really like your idea here. there's a problem though ... these changes would introduce a breaking change for those who already are already using the theme as a submodule. If they pull these changes, they won't have `'../../assets/sass/custom'` or `'../../assets/sass/variables'`. SASS will error out on this one. 

The javascript custom file looks okay because you included a neat check 33f87efb678fb9c02a88b3340b.

Once we move past that blindspot, the rest of the PR looks good.

**Comment by rootwork** [comment]
Surprisingly, the Sass compiler (at least as it's configured in Hugo extended) doesn't seem to complain about missing files being included. But it'd be better code to add a similar check for them, and since the Sass files are being processed as templates that should be easy. I'll do that and push an update.

**Comment by onweru** [comment]
> doesn't seem to complain about missing files being included

**Comment by onweru** [comment]
> doesn't seem to complain about missing files being included

Interesting @rootwork, I will confirm this. If it doesn’t break things, I will merge.

**Comment by onweru** [comment]
@rootwork,

Confirmed! Thanks for contributing, if you could help with documenting this [in the README](https://github.com/chipzoller/hugo-clarity#custom-css-and-js), that would be great! If not, I will get to it soon enough.

Merging.

**Pull request merged**
