### PR TITLE
Fix icons/src property so that it does not 404

### LINKED ISSUE #458: [Bug] Icon src property doesn't point to the correct path for the icons in static/icons/site.webmanifest
### I confirm:

- [X] I am running the [extended version of Hugo version 0.91.0 or above](https://github.com/chipzoller/hugo-clarity/blob/master/README.md#prerequisites) to build my site.
- [X] I have read the [Hugo Clarity theme documentation](https://github.com/chipzoller/hugo-clarity/blob/master/README.md).
- [X] I have used the [example site's config files](https://github.com/chipzoller/hugo-clarity/tree/master/exampleSite/config/_default) as reference.
- [X] I have reviewed [other issues in this repository](https://github.com/chipzoller/hugo-clarity/issues) and mine is not recorded.

### Hugo version

0.121.1

### Where is this bug showing up?

Other: Both, neither, or somewhere else.

### Operating system

Ubuntu 23.04

### Browser (if applicable)

_No response_

### Current behavior

Current site.webmanifest file:
{
    "name": "",
    "short_name": "",
    "icons": [
        {
            "src": "/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/android-chrome-256x256.png",
            "sizes": "256x256",
            "type": "image/png"
        }
    ],
    "theme_color": "#ffffff",
    "background_color": "#ffffff",
    "display": "standalone"
}

The src property of the Icon object is a root relative link pointing to an icon in the root of the site. The icon however is in /icons/ directory.

### Expected behavior

Point the src property at the /icons directory in the root of the site:
{
    "name": "",
    "short_name": "",
    "icons": [
        {
            "src": "/icons/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/icons/android-chrome-256x256.png",
            "sizes": "256x256",
            "type": "image/png"
        }
    ],
    "theme_color": "#ffffff",
    "background_color": "#ffffff",
    "display": "standalone"
}

### Steps to reproduce

Deploy the theme example site and then request the /icons/site.webmanifest file via curl. Then request one of the icons from the URL in the src property. curl will return a 404.

### Relevant log output

_No response_

### Related code

_No response_

### Preferred solution

Change the Icons/src properties to point to the icons directory in the root such as `/icons/x.png`. Or, remove the opening slash such as `x.png`. If no leading slash is present, the spec assumes that the file is in the same directory as the `site.webmanifest` file.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by digitalbricklayer**
Fix for the icons in site.webmanifest pointing to the wrong location. The src property points to the root of the site instead of the icons directory.

## Pull Request type

Please check the type of change your PR introduces:

- [X] Bug-fix
- [ ] Feature (functionality, design, translations, etc.)
- [ ] Documentation change
- [ ] Project management (tests, CI, GitHub configuration, etc.)
- [ ] Other (please describe):

## Current state

Closes #458

## Proposed changes

Changes the icon src to be relative to the icons folder. According to the site.webmanifest spec, if you specify a relative link, it assumes that the link is relative to the location of the site.webmanifest file itself.

## Checklist

- [X] **Bug-fixes and new features:** I have tested locally with the [latest release of Hugo extended](https://github.com/gohugoio/hugo/releases). This requirement is [a standard](https://github.com/gohugoio/hugoThemes#theme-maintenance).
- [X] **Bug-fixes, new features, and doc changes:** I have updated the relevant documentation as part of this PR.
- [x] **All PRs:** I have [signed off](https://github.com/chipzoller/hugo-clarity/blob/master/CONTRIBUTING.md#how-to-submit-a-pull-request) (using `git commit -s ...`), or if not possible due to developer environment constraints, will comment below confirming that I am adhering to the [Developer Certificate of Origin](https://probot.github.io/apps/dco/).

I am adhering to the Developer Certificate of Origin.

### CODE REVIEW

**Comment by chipzoller** [comment]
Please sign off on your commits.

**Comment by digitalbricklayer** [comment]
I am adhering to the [Developer Certificate of Origin](https://probot.github.io/apps/dco/).

**Comment by chipzoller** [comment]
Your commits must be signed.

**Comment by digitalbricklayer** [comment]
Can confirm change is now signed-off.

**Review by onweru — APPROVED** [review]

**Pull request merged**
