### PR TITLE
Add hooks

### PR DESCRIPTION
**Pull request by razonyang**
Hooks provide a way to add code on a page. For example(search engine webmaster verification: Google, Bing, Baidu etc):

```html
<meta name="google-site-verification" content="xxx" />
```

This way is more flexible than define a parameter for each search engines.

### CODE REVIEW

**Comment by onweru** [comment]
Interesting idea. It does, however, introduce the same problem described by @rootwork in #28.

**Comment by razonyang** [comment]
I don't think there will be such a problem here. I create my own hooks in `layouts/partials/hooks/*`(not `themes/hugo-clarity/layouts/partials/hooks/*`), so the theme can be a git submodule, and we can also track modifications, because we just override these files not modify them.

**Comment by onweru** [comment]
Fair enough, could you add comments on the hook files placeholders e.g layouts/partials/hooks/body-end.html, indicating that the contents of those files should only be overridden (i.e never edited directly)?

**Comment by razonyang** [comment]
I documented this in `README.md`.

**Pull request merged**
