### PR TITLE
fix: onhover link icon color in dark mode

### PR DESCRIPTION
**Pull request by barefootstache**
fix: onhover link icon color in dark mode from the existing black to white.

Cannot use the existing system, since the `link.svg` icon is being imported as an image, thus one needs to use the filter property in CSS.

### CODE REVIEW

**Review by onweru — APPROVED** [review]

**Comment by chipzoller** [comment]
Thanks for the contribution!

**Comment by gefloh** [comment]
@barefootstache @chipzoller  Hm for me this destroys the colors of the icon in the footer, left of the copyright in dark mode. In the example site this looks ok, but if you use a more sophisticated icon with more colors, this is not good.

**Comment by chipzoller** [comment]
Can you provide an example?

**Comment by gefloh** [comment]
Before: 
grafik

Now:
grafik

**Comment by barefootstache** [comment]
If this is the only place, then we could prepend

```
body > :not(footer)
```

into the variables to catch the case with the icon in the footer to stay static between dark/light mode.

**Pull request merged**
